namespace GonkNote.Services;

/// <summary>
/// Die englischen Texte. Gleiche Schlüssel wie <see cref="LocGerman"/>; was hier fehlt,
/// erscheint auf Deutsch.
/// </summary>
internal static class LocEnglish
{
    public static readonly Dictionary<string, string> Texts = new()
    {
        // ---- Menu bar (underscore = access key) ----
        ["Menu.File"] = "_File",
        ["Menu.File.NewFolder"] = "New _folder",
        ["Menu.File.NewNotebook"] = "New _notebook",
        ["Menu.File.NewWhiteboard"] = "New _whiteboard",
        ["Menu.File.NewText"] = "New _text document",
        ["Menu.File.Import"] = "_Import document… (DOCX / Markdown)",
        ["Menu.File.Export"] = "_Export… (PDF / DOCX / Markdown)",
        ["Menu.File.Save"] = "_Save",
        ["Menu.File.SaveAll"] = "Save _all",
        ["Menu.File.Quit"] = "_Quit",
        ["Menu.View"] = "_View",
        ["Menu.View.Sidebar"] = "_Sidebar",
        ["Menu.View.Theme"] = "Toggle _dark/light mode",
        ["Menu.View.Language"] = "_Language",
        ["Menu.View.Language.German"] = "German",
        ["Menu.View.Language.English"] = "English",
        ["Menu.Help"] = "_Help",
        ["Menu.Help.About"] = "About _Gonk Note",

        // ---- Sidebar ----
        ["Sidebar.Toggle"] = "Show/hide sidebar (Ctrl+B)",
        ["Sidebar.Pinned"] = "PINNED",
        ["Sidebar.SwitchTheme"] = "Switch theme",
        ["Sidebar.ThemeTooltip"] = "Dark/light mode (Ctrl+T)",

        // ---- New documents ----
        ["New.Folder"] = "New folder",
        ["New.Notebook"] = "New notebook",
        ["New.Whiteboard"] = "New whiteboard",
        ["New.Text"] = "New text document",

        // ---- Folder tree ----
        ["Tree.Open"] = "Open",
        ["Tree.Rename"] = "Rename",
        ["Tree.Delete"] = "Delete",
        ["Tree.Favorite"] = "Favourite",
        ["Tree.IconColor"] = "Icon colour",
        ["Tree.IconColor.Auto"] = "Automatic (folder colour)",
        ["Tree.IconColor.AutoTooltip"] = "Takes the colour of the parent folder",
        ["Tree.IconColor.Custom"] = "Custom colour…",

        // ---- Colours ----
        ["Color.Blue"] = "Blue",
        ["Color.Teal"] = "Teal",
        ["Color.Pink"] = "Pink",
        ["Color.Purple"] = "Purple",
        ["Color.Red"] = "Red",
        ["Color.Orange"] = "Orange",
        ["Color.Yellow"] = "Yellow",
        ["Color.Green"] = "Green",
        ["Color.Gray"] = "Grey",

        // ---- Gallery (start view without an open document) ----
        ["Gallery.Back"] = "Back",
        ["Gallery.New"] = "New",
        ["Gallery.Empty.Title"] = "Nothing here yet",
        ["Gallery.Empty.Hint"] = "Create something via “New” or the sidebar.",
        ["Gallery.Options"] = "Options",

        // ---- Window / tabs ----
        ["Window.CloseTab"] = "Close (Ctrl+W)",
        ["Window.Minimize"] = "Minimise",
        ["Window.Restore"] = "Restore",
        ["Window.Close"] = "Close",

        // ---- Keyboard shortcuts (menu display only) ----
        ["Shortcut.Save"] = "Ctrl+S",
        ["Shortcut.SaveAll"] = "Ctrl+Shift+S",
        ["Shortcut.Quit"] = "Alt+F4",
        ["Shortcut.Sidebar"] = "Ctrl+B",
        ["Shortcut.Theme"] = "Ctrl+T",
        ["Shortcut.Rename"] = "F2",
        ["Shortcut.Delete"] = "Del",

        // ---- Texts set from code ----
        ["Gallery.Root"] = "Documents",
        ["Item.CopySuffix"] = " (copy)",
        ["Import.Filter"] = "Documents (*.docx;*.md)|*.docx;*.md|Word documents (*.docx)|*.docx",
        ["Gallery.DateFormat"] = "d MMM yyyy, HH:mm",

        // ---- Whiteboard / notebook ----
        ["Tool.Hand"] = "Hand",
        ["Tool.Hand.Tip"] = "Hand (H) – pan the canvas (or middle mouse button)",
        ["Tool.Pen"] = "Pen (S)",
        ["Tool.SmoothPen"] = "Shape pen (G) – recognises lines, circles, rectangles &amp; co., smooths curves",
        ["Tool.Pencil"] = "Pencil (B)",
        ["Tool.Highlighter"] = "Highlighter (M)",
        ["Tool.Eraser"] = "Eraser (E)",
        ["Tool.Lasso"] = "Lasso select (L) – circle objects (only what is ~fully enclosed)",
        ["Tool.Move"] = "Move",
        ["Tool.Move.Tip"] = "Move (V) – click an object directly, then move or scale it",
        ["Tool.Text"] = "Text box (T)",
        ["Tool.Shape.Rect"] = "Rectangle (F)",
        ["Tool.Shape.Line"] = "Line",
        ["Tool.Shape.Arrow"] = "Arrow",
        ["Tool.Shape.Ellipse"] = "Ellipse",
        ["Tool.Shape.Triangle"] = "Triangle",
        ["Tool.Chart"] = "Chart",
        ["Tool.Chart.Tip"] = "Insert chart (column, bar, line, scatter, pie, radar)",
        ["Tool.Sticky"] = "Sticky note (N) – place a coloured note",
        ["Tool.Sticker"] = "Sticker",
        ["Tool.Sticker.Tip"] = "Sticker – insert a picture sticker from the collection",
        ["Tool.Ruler"] = "Ruler",
        ["Tool.Ruler.Tip"] = "Ruler (R) – straight lines along the edge; drag the body to move, the handle to rotate",
        ["Tool.SetSquare"] = "Set square",
        ["Tool.SetSquare.Tip"] = "Set square (D) – straight lines along three edges, with an angle scale; drag the body to move, the handle to rotate",
        ["Color.Auto"] = "Default (black on light pages, white on dark ones)",
        ["Color.Custom"] = "Custom colour",
        ["Color.Pick"] = "Choose colour (colour wheel / hex)",
        ["Size.Tip"] = "Line width – press and hold for number entry",
        ["Action.Delete"] = "Delete",
        ["Action.Undo"] = "Undo (Ctrl+Z)",
        ["Action.Redo"] = "Redo (Ctrl+Y)",
        ["Zoom.Out"] = "Zoom out",
        ["Zoom.Reset"] = "Reset zoom",
        ["Zoom.In"] = "Zoom in",
        ["Wb.InsertFile"] = "Insert file",
        ["Wb.InsertFile.Tip"] = "Insert file – image, PDF or Word (pages selectable for PDF/Word; as new pages in a notebook, as image pages on a whiteboard); also via Ctrl+V or drag &amp; drop",
        ["Wb.Settings"] = "Settings",
        ["Wb.Settings.Tip"] = "Settings (page, shapes, text, cover)",
        ["Wb.Settings.Close"] = "Close settings",
        ["Page.Previous"] = "Previous page",
        ["Page.Next"] = "Next page",
        ["Page.Add"] = "New page",
        ["Page.Delete"] = "Delete page",
        ["Page.Label"] = "Page {0} / {1}",
        ["Settings.Page"] = "Page",
        ["Settings.Page.Pattern"] = "Pattern",
        ["Settings.Page.Blank"] = "Blank",
        ["Settings.Page.Lines"] = "Ruled",
        ["Settings.Page.Grid"] = "Squared",
        ["Settings.Page.Dots"] = "Dotted",
        ["Settings.Page.Shade"] = "Shade",
        ["Settings.Page.Shade.Auto"] = "Follow app theme",
        ["Settings.Page.Shade.Light"] = "Light",
        ["Settings.Page.Shade.Dark"] = "Dark",
        ["Settings.Page.Format"] = "Format",
        ["Settings.Page.Orientation"] = "Orientation",
        ["Settings.Page.Portrait"] = "Portrait",
        ["Settings.Page.Landscape"] = "Landscape",
        ["Settings.Page.AsDefault"] = "Use as default for new pages",
        ["Settings.Shapes"] = "Shapes",
        ["Settings.Shapes.Hint"] = "Pick the shape in the toolbar; set the fill here.",
        ["Settings.Shapes.FillToggle"] = "Fill on/off",
        ["Settings.Shapes.FillColor"] = "Choose fill colour",
        ["Settings.Shapes.Fill"] = "Fill",
        ["Settings.Shapes.Opacity"] = "Opacity",
        ["Settings.Text"] = "Text",
        ["Settings.Text.ColorTip"] = "Choose text colour (also used as ink colour)",
        ["Settings.Text.Color"] = "Text colour",
        ["Settings.Text.BgTip"] = "Background colour of the text box",
        ["Settings.Text.Bg"] = "Background",
        ["Settings.Text.Transparent"] = "Transparent",
        ["Settings.Text.Font"] = "Font",
        ["Settings.Text.Hint"] = "Applies to new text boxes and to the one being edited or selected.",
        ["Settings.Sticky"] = "Sticky notes",
        ["Settings.Sticky.Color"] = "Note colour",
        ["Settings.Sticky.CustomColor"] = "Choose a custom note colour",
        ["Settings.Sticky.Hint"] = "Tap the sheet to place a note, then tap it to write. Move/scale it with the move or lasso tool.",
        ["Settings.Sticker.Hint"] = "A click inserts the sticker in the middle of the sheet. Then place and scale it with the move tool (V).",
        ["Settings.Sticker.Add"] = "Add sticker",
        ["Settings.Cover"] = "Cover",
        ["Settings.Cover.Gradient"] = "Gradient",
        ["Settings.Cover.StartColor"] = "Choose start colour",
        ["Settings.Cover.Start"] = "Start",
        ["Settings.Cover.EndColor"] = "Choose end colour",
        ["Settings.Cover.End"] = "End",
        ["Settings.Cover.Font"] = "Font",
        ["Settings.Cover.Image"] = "Image as cover",
        ["Settings.Cover.ChooseImage"] = "Choose image…",
        ["Settings.Cover.RemoveImage"] = "Remove",
        ["Settings.Cover.ImageHint"] = "The image replaces the gradient and the title on the cover.",
        ["Settings.Cover.Presets"] = "Templates",
        ["Quick.Cut.Tip"] = "Cut (Ctrl+X)",
        ["Quick.Cut"] = "Cut",
        ["Quick.Copy.Tip"] = "Copy (Ctrl+C)",
        ["Quick.Copy"] = "Copy",
        ["Quick.Duplicate.Tip"] = "Duplicate (Ctrl+D)",
        ["Quick.Duplicate"] = "Duplicate",
        ["Quick.Paste.Tip"] = "Paste (Ctrl+V)",
        ["Quick.Paste"] = "Paste",
        ["Quick.Ocr"] = "Recognise text (OCR)",
        ["Quick.Delete.Tip"] = "Delete (Del)",
        ["Quick.SelectAll.Tip"] = "Select all (Ctrl+A)",
        ["Quick.SelectAll"] = "Select all",
        ["Busy.Importing"] = "Importing…",
        ["Busy.Pdf"] = "Importing PDF…",
        ["Busy.Pdf.Progress"] = "Importing PDF…  {0} / {1}",
        ["Busy.Docx"] = "Inserting Word document…",
        ["Page.Cover"] = "Cover",
        ["Size.Eraser.Tip"] = "Eraser size – press and hold for number entry",
    };
}
