namespace GonkNote.Services;

/// <summary>
/// Die deutschen Texte – die Vorlage. Was hier steht, ist die Wahrheit; die englische
/// Tabelle übersetzt dieselben Schlüssel. Fehlt dort einer, erscheint der deutsche Text.
/// <para>Schlüssel sind nach Bereichen gruppiert: <c>Menu.*</c>, <c>Tree.*</c>, …</para>
/// </summary>
internal static class LocGerman
{
    public static readonly Dictionary<string, string> Texts = new()
    {
        // ---- Menüleiste (Unterstrich = Zugriffstaste) ----
        ["Menu.File"] = "_Datei",
        ["Menu.File.NewFolder"] = "Neuer _Ordner",
        ["Menu.File.NewNotebook"] = "Neues _Notizbuch",
        ["Menu.File.NewWhiteboard"] = "Neues _Whiteboard",
        ["Menu.File.NewText"] = "Neues _Textdokument",
        ["Menu.File.Import"] = "Dokument _importieren… (DOCX / Markdown)",
        ["Menu.File.Export"] = "_Exportieren… (PDF / DOCX / Markdown)",
        ["Menu.File.Save"] = "_Speichern",
        ["Menu.File.SaveAll"] = "_Alle speichern",
        ["Menu.File.Quit"] = "_Beenden",
        ["Menu.View"] = "_Ansicht",
        ["Menu.View.Sidebar"] = "_Seitenleiste",
        ["Menu.View.Theme"] = "_Dark/Light Mode umschalten",
        ["Menu.View.Language"] = "S_prache",
        ["Menu.View.Language.German"] = "Deutsch",
        ["Menu.View.Language.English"] = "Englisch",
        ["Menu.Help"] = "_Hilfe",
        ["Menu.Help.About"] = "Über _Gonk Note",

        // ---- Seitenleiste ----
        ["Sidebar.Toggle"] = "Seitenleiste ein-/ausblenden (Strg+B)",
        ["Sidebar.Pinned"] = "ANGEPINNT",
        ["Sidebar.SwitchTheme"] = "Design wechseln",
        ["Sidebar.ThemeTooltip"] = "Dark/Light Mode (Strg+T)",

        // ---- Neue Dokumente (Schaltflächen, Kontextmenü, Galerie) ----
        ["New.Folder"] = "Neuer Ordner",
        ["New.Notebook"] = "Neues Notizbuch",
        ["New.Whiteboard"] = "Neues Whiteboard",
        ["New.Text"] = "Neues Textdokument",

        // ---- Ordnerbaum ----
        ["Tree.Open"] = "Öffnen",
        ["Tree.Rename"] = "Umbenennen",
        ["Tree.Delete"] = "Löschen",
        ["Tree.Favorite"] = "Favorit",
        ["Tree.IconColor"] = "Symbolfarbe",
        ["Tree.IconColor.Auto"] = "Automatisch (Ordnerfarbe)",
        ["Tree.IconColor.AutoTooltip"] = "Übernimmt die Farbe des übergeordneten Ordners",
        ["Tree.IconColor.Custom"] = "Eigene Farbe…",

        // ---- Farben ----
        ["Color.Blue"] = "Blau",
        ["Color.Teal"] = "Türkis",
        ["Color.Pink"] = "Pink",
        ["Color.Purple"] = "Lila",
        ["Color.Red"] = "Rot",
        ["Color.Orange"] = "Orange",
        ["Color.Yellow"] = "Gelb",
        ["Color.Green"] = "Grün",
        ["Color.Gray"] = "Grau",

        // ---- Galerie (Startansicht ohne geöffnetes Dokument) ----
        ["Gallery.Back"] = "Zurück",
        ["Gallery.New"] = "Neu",
        ["Gallery.Empty.Title"] = "Noch nichts hier",
        ["Gallery.Empty.Hint"] = "Erstelle etwas über „Neu“ oder die Seitenleiste.",
        ["Gallery.Options"] = "Optionen",

        // ---- Fenster / Tabs ----
        ["Window.CloseTab"] = "Schließen (Strg+W)",
        ["Window.Minimize"] = "Minimieren",
        ["Window.Restore"] = "Wiederherstellen",
        ["Window.Close"] = "Schließen",

        // ---- Tastenkürzel (nur die Anzeige im Menü) ----
        ["Shortcut.Save"] = "Strg+S",
        ["Shortcut.SaveAll"] = "Strg+Umschalt+S",
        ["Shortcut.Quit"] = "Alt+F4",
        ["Shortcut.Sidebar"] = "Strg+B",
        ["Shortcut.Theme"] = "Strg+T",
        ["Shortcut.Rename"] = "F2",
        ["Shortcut.Delete"] = "Entf",

        // ---- Texte, die der Code setzt ----
        ["Gallery.Root"] = "Dokumente",
        ["Item.CopySuffix"] = " (Kopie)",
        ["Import.Filter"] = "Dokumente (*.docx;*.md)|*.docx;*.md|Word-Dokumente (*.docx)|*.docx",
        ["Gallery.DateFormat"] = "d. MMM yyyy, HH:mm",

        // ---- Whiteboard / Notizbuch ----
        ["Tool.Hand"] = "Hand",
        ["Tool.Hand.Tip"] = "Hand (H) – Leinwand verschieben (oder mittlere Maustaste)",
        ["Tool.Pen"] = "Stift (S)",
        ["Tool.SmoothPen"] = "Formen-Stift (G) – erkennt Linien, Kreise, Rechtecke &amp; Co., glättet Kurven",
        ["Tool.Pencil"] = "Bleistift (B)",
        ["Tool.Highlighter"] = "Textmarker (M)",
        ["Tool.Eraser"] = "Radiergummi (E)",
        ["Tool.Lasso"] = "Lasso-Auswahl (L) – Objekte umkreisen (nur was ~vollständig umschlossen ist)",
        ["Tool.Move"] = "Verschieben",
        ["Tool.Move.Tip"] = "Verschieben (V) – Objekt direkt anklicken, dann verschieben oder skalieren",
        ["Tool.Text"] = "Textfeld (T)",
        ["Tool.Shape.Rect"] = "Rechteck (F)",
        ["Tool.Shape.Line"] = "Linie",
        ["Tool.Shape.Arrow"] = "Pfeil",
        ["Tool.Shape.Ellipse"] = "Ellipse",
        ["Tool.Shape.Triangle"] = "Dreieck",
        ["Tool.Chart"] = "Diagramm",
        ["Tool.Chart.Tip"] = "Diagramm einfügen (Säulen, Balken, Linie, Punkt, Kuchen, Radar)",
        ["Tool.Sticky"] = "Notizzettel (N) – farbigen Klebezettel setzen",
        ["Tool.Sticker"] = "Sticker",
        ["Tool.Sticker.Tip"] = "Sticker – Bild-Aufkleber aus der Sammlung einfügen",
        ["Tool.Ruler"] = "Lineal",
        ["Tool.Ruler.Tip"] = "Lineal (R) – gerade Linien entlang der Kante; Körper ziehen = bewegen, Griff ziehen = drehen",
        ["Tool.SetSquare"] = "Geodreieck",
        ["Tool.SetSquare.Tip"] = "Geodreieck (D) – gerade Linien an drei Kanten, mit Winkelskala; Körper ziehen = bewegen, Griff ziehen = drehen",
        ["Color.Auto"] = "Standard (Schwarz auf hellen, Weiß auf dunklen Seiten)",
        ["Color.Custom"] = "Eigene Farbe",
        ["Color.Pick"] = "Farbe wählen (Farbrad / Hex)",
        ["Size.Tip"] = "Strichstärke – lange drücken für Zahleneingabe",
        ["Action.Delete"] = "Löschen",
        ["Action.Undo"] = "Rückgängig (Strg+Z)",
        ["Action.Redo"] = "Wiederholen (Strg+Y)",
        ["Zoom.Out"] = "Verkleinern",
        ["Zoom.Reset"] = "Zoom zurücksetzen",
        ["Zoom.In"] = "Vergrößern",
        ["Wb.InsertFile"] = "Datei einfügen",
        ["Wb.InsertFile.Tip"] = "Datei einfügen – Bild, PDF oder Word (bei PDF/Word Seiten auswählbar; im Notizbuch als neue Seiten, im Whiteboard als Bild-Seiten); auch per Strg+V oder Drag &amp; Drop",
        ["Wb.Settings"] = "Einstellungen",
        ["Wb.Settings.Tip"] = "Einstellungen (Seite, Formen, Text, Cover)",
        ["Wb.Settings.Close"] = "Einstellungen schließen",
        ["Page.Previous"] = "Vorherige Seite",
        ["Page.Next"] = "Nächste Seite",
        ["Page.Add"] = "Neue Seite",
        ["Page.Delete"] = "Seite löschen",
        ["Page.Label"] = "Seite 1 / 1",
        ["Settings.Page"] = "Seite",
        ["Settings.Page.Pattern"] = "Muster",
        ["Settings.Page.Blank"] = "Blanko",
        ["Settings.Page.Lines"] = "Liniert",
        ["Settings.Page.Grid"] = "Kariert",
        ["Settings.Page.Dots"] = "Punktiert",
        ["Settings.Page.Shade"] = "Farbton",
        ["Settings.Page.Shade.Auto"] = "Wie App-Design",
        ["Settings.Page.Shade.Light"] = "Hell",
        ["Settings.Page.Shade.Dark"] = "Dunkel",
        ["Settings.Page.Format"] = "Format",
        ["Settings.Page.Orientation"] = "Ausrichtung",
        ["Settings.Page.Portrait"] = "Hochformat",
        ["Settings.Page.Landscape"] = "Querformat",
        ["Settings.Page.AsDefault"] = "Als Standard für neue Seiten",
        ["Settings.Shapes"] = "Formen",
        ["Settings.Shapes.Hint"] = "Form wählst du in der Werkzeugleiste; hier die Füllung.",
        ["Settings.Shapes.FillToggle"] = "Füllung ein/aus",
        ["Settings.Shapes.FillColor"] = "Füllfarbe wählen",
        ["Settings.Shapes.Fill"] = "Füllung",
        ["Settings.Shapes.Opacity"] = "Deckkraft",
        ["Settings.Text"] = "Text",
        ["Settings.Text.ColorTip"] = "Textfarbe wählen (gilt auch als Tintenfarbe)",
        ["Settings.Text.Color"] = "Textfarbe",
        ["Settings.Text.BgTip"] = "Hintergrundfarbe des Textfelds",
        ["Settings.Text.Bg"] = "Hintergrund",
        ["Settings.Text.Transparent"] = "Transparent",
        ["Settings.Text.Font"] = "Schriftart",
        ["Settings.Text.Hint"] = "Wirkt auf neue Textfelder sowie das gerade bearbeitete bzw. ausgewählte.",
        ["Settings.Sticky"] = "Notizzettel",
        ["Settings.Sticky.Color"] = "Zettelfarbe",
        ["Settings.Sticky.CustomColor"] = "Eigene Zettelfarbe wählen",
        ["Settings.Sticky.Hint"] = "Zum Setzen aufs Blatt tippen, dann tippen zum Beschriften. Verschieben/Skalieren mit dem Verschieben- oder Lasso-Werkzeug.",
        ["Settings.Sticker.Hint"] = "Klick fügt den Sticker mittig aufs Blatt ein. Danach mit dem Verschieben-Werkzeug (V) platzieren und skalieren.",
        ["Settings.Sticker.Add"] = "Sticker hinzufügen",
        ["Settings.Cover"] = "Cover",
        ["Settings.Cover.Gradient"] = "Farbverlauf",
        ["Settings.Cover.StartColor"] = "Startfarbe wählen",
        ["Settings.Cover.Start"] = "Start",
        ["Settings.Cover.EndColor"] = "Endfarbe wählen",
        ["Settings.Cover.End"] = "Ende",
        ["Settings.Cover.Font"] = "Schrift",
        ["Settings.Cover.Image"] = "Bild als Cover",
        ["Settings.Cover.ChooseImage"] = "Bild wählen…",
        ["Settings.Cover.RemoveImage"] = "Entfernen",
        ["Settings.Cover.ImageHint"] = "Das Bild ersetzt Verlauf und Titel auf dem Cover.",
        ["Settings.Cover.Presets"] = "Vorlagen",
        ["Quick.Cut.Tip"] = "Ausschneiden (Strg+X)",
        ["Quick.Cut"] = "Ausschneiden",
        ["Quick.Copy.Tip"] = "Kopieren (Strg+C)",
        ["Quick.Copy"] = "Kopieren",
        ["Quick.Duplicate.Tip"] = "Duplizieren (Strg+D)",
        ["Quick.Duplicate"] = "Duplizieren",
        ["Quick.Paste.Tip"] = "Einfügen (Strg+V)",
        ["Quick.Paste"] = "Einfügen",
        ["Quick.Ocr"] = "Text erkennen (OCR)",
        ["Quick.Delete.Tip"] = "Löschen (Entf)",
        ["Quick.SelectAll.Tip"] = "Alles auswählen (Strg+A)",
        ["Quick.SelectAll"] = "Alles auswählen",
        ["Busy.Importing"] = "Wird importiert…",
        ["Busy.Pdf"] = "PDF wird importiert…",
        ["Busy.Pdf.Progress"] = "PDF wird importiert…  {0} / {1}",
        ["Busy.Docx"] = "Word-Dokument wird eingefügt…",
        ["Page.Cover"] = "Cover",
        ["Size.Eraser.Tip"] = "Radierergröße – lange drücken für Zahleneingabe",
    };
}
