namespace GonkNote.Services;

/// <summary>
/// Die englischen Texte. Gleiche Schlüssel wie <see cref="LocGerman"/>; was hier fehlt,
/// erscheint auf Deutsch.
/// </summary>
internal static class LocEnglish
{
    public static readonly Dictionary<string, string> Texts = new()
    {
        // ---- Menu bar (underscore = access key) ----
        ["Menu.File"] = "_File",
        ["Menu.File.NewFolder"] = "New _folder",
        ["Menu.File.NewNotebook"] = "New _notebook",
        ["Menu.File.NewWhiteboard"] = "New _whiteboard",
        ["Menu.File.NewText"] = "New _text document",
        // Gegenstueck zu LocGerman (§4.28): Formatliste raus, der Dateidialog nennt sie.
        ["Menu.File.Import"] = "_Import document…",
        ["Menu.File.Export"] = "_Export…",
        ["Menu.File.Save"] = "_Save",
        ["Menu.File.SaveAll"] = "Save _all",
        ["Menu.File.Quit"] = "_Quit",
        ["Menu.View"] = "_View",
        ["Menu.View.Sidebar"] = "_Sidebar",
        ["Menu.View.Theme"] = "Toggle _dark/light mode",
        ["Menu.View.Language"] = "_Language",
        ["Menu.View.Language.German"] = "German",
        ["Menu.View.Language.English"] = "English",
        ["Menu.Help"] = "_Help",
        // Zugriffstaste bewusst "s": "About _Gonk Note" belegt bereits das G.
        ["Menu.Help.Guide"] = "Getting _started",
        ["Menu.Help.About"] = "About _Gonk Note",

        // ---- Sidebar ----
        ["Sidebar.Toggle"] = "Show/hide sidebar (Ctrl+B)",
        ["Sidebar.Pinned"] = "PINNED",
        ["Sidebar.SwitchTheme"] = "Switch theme",
        ["Sidebar.ThemeTooltip"] = "Dark/light mode (Ctrl+T)",

        // ---- New documents ----
        ["New.Folder"] = "New folder",
        ["New.Notebook"] = "New notebook",
        ["New.Whiteboard"] = "New whiteboard",
        ["New.Text"] = "New text document",

        // ---- Folder tree ----
        ["Tree.Open"] = "Open",
        ["Tree.Rename"] = "Rename",
        ["Tree.Delete"] = "Delete",
        ["Tree.Favorite"] = "Favourite",
        // Context menu in the folder tree – the label changes with the state.
        // Were hard-coded in German inside TreeItemViewModel until phase 2.
        ["Tree.Pin"] = "Pin",
        ["Tree.Unpin"] = "Unpin",
        ["Tree.MarkFavorite"] = "Mark as favourite",
        ["Tree.UnmarkFavorite"] = "Remove favourite",
        ["Tree.IconColor"] = "Icon colour",
        ["Tree.IconColor.Auto"] = "Automatic (folder colour)",
        ["Tree.IconColor.AutoTooltip"] = "Takes the colour of the parent folder",
        ["Tree.IconColor.Custom"] = "Custom colour…",

        // ---- Colours ----
        ["Color.Blue"] = "Blue",
        ["Color.Teal"] = "Teal",
        ["Color.Pink"] = "Pink",
        ["Color.Purple"] = "Purple",
        ["Color.Red"] = "Red",
        ["Color.Orange"] = "Orange",
        ["Color.Yellow"] = "Yellow",
        ["Color.Green"] = "Green",
        ["Color.Gray"] = "Grey",

        // ---- Gallery (start view without an open document) ----
        ["Gallery.Back"] = "Back",
        ["Gallery.New"] = "New",
        ["Gallery.Empty.Title"] = "Nothing here yet",
        ["Gallery.Empty.Hint"] = "Create something via “New” or the sidebar.",
        ["Gallery.Options"] = "Options",

        // ---- Window / tabs ----
        ["Window.CloseTab"] = "Close (Ctrl+W)",
        ["Window.Minimize"] = "Minimise",
        ["Window.Restore"] = "Restore",
        ["Window.Close"] = "Close",

        // ---- Keyboard shortcuts (menu display only) ----
        ["Shortcut.Save"] = "Ctrl+S",
        ["Shortcut.SaveAll"] = "Ctrl+Shift+S",
        ["Shortcut.Quit"] = "Alt+F4",
        ["Shortcut.Sidebar"] = "Ctrl+B",
        ["Shortcut.Theme"] = "Ctrl+T",
        ["Shortcut.Rename"] = "F2",
        ["Shortcut.Delete"] = "Del",
        // Gegenstuecke zu Shortcut.Cut/Copy/Paste in LocGerman (§4.74).
        ["Shortcut.Cut"] = "Ctrl+X",
        ["Shortcut.Copy"] = "Ctrl+C",
        ["Shortcut.Paste"] = "Ctrl+V",

        // ---- Texts set from code ----
        ["Gallery.Root"] = "Documents",
        ["Item.CopySuffix"] = " (copy)",
        ["Gallery.DateFormat"] = "d MMM yyyy, HH:mm",

        // Titles and format lists of the file dialogs. The extensions live in the code
        // (GonkNote.Core.Platform.FileFilter); only what the user reads is here.
        ["Dialog.ImportTitle"] = "Import document",
        ["Dialog.ExportTitle"] = "Export",
        ["Filter.Documents"] = "Documents (*.docx;*.md)",
        ["Filter.Word"] = "Word document (*.docx)",
        ["Filter.Markdown"] = "Markdown (*.md)",
        ["Filter.AllFiles"] = "All files (*.*)",
        ["Filter.Pdf"] = "PDF document (*.pdf)",
        ["Filter.Png"] = "PNG image(s) (*.png)",
        ["Filter.Images"] = "Images (*.png;*.jpg;*.jpeg;*.webp)",
        ["Filter.ImagesImport"] = "Images (*.png;*.jpg;*.jpeg;*.bmp;*.gif;*.webp;*.svg)",
        ["Filter.InsertAll"] = "Images, PDF & Word",

        // ---- Whiteboard / notebook ----
        ["Tool.Hand"] = "Hand",
        ["Tool.Hand.Tip"] = "Hand (H) – pan the canvas (or middle mouse button)",
        ["Tool.Pen"] = "Pen (S)",
        ["Tool.SmoothPen"] = "Shape pen (G) – recognises lines, circles, rectangles &amp; co., smooths curves",
        ["Tool.Pencil"] = "Pencil (B)",
        ["Tool.Highlighter"] = "Highlighter (M)",
        ["Tool.Eraser"] = "Eraser (E)",
        ["Tool.Lasso"] = "Lasso select (L) – circle objects (only what is ~fully enclosed)",
        ["Tool.Move"] = "Move",
        ["Tool.Move.Tip"] = "Move (V) – click an object directly, then move or scale it",
        ["Tool.Text"] = "Text box (T)",
        ["Tool.Shape.Rect"] = "Rectangle (F)",
        ["Tool.Shape.Line"] = "Line",
        ["Tool.Shape.Arrow"] = "Arrow",
        ["Tool.Shape.Ellipse"] = "Ellipse",
        ["Tool.Shape.Triangle"] = "Triangle",
        ["Tool.Chart"] = "Chart",
        ["Tool.Chart.Tip"] = "Insert chart (column, bar, line, scatter, pie, radar)",
        ["Tool.Sticky"] = "Sticky note (N) – place a coloured note",
        ["Tool.Sticker"] = "Sticker",
        ["Tool.Sticker.Tip"] = "Sticker – insert a picture sticker from the collection",
        ["Tool.Ruler"] = "Ruler",
        ["Tool.Ruler.Tip"] = "Ruler (R) – straight lines along the edge; drag the body to move, the handle to rotate",
        ["Tool.SetSquare"] = "Set square",
        ["Tool.SetSquare.Tip"] = "Set square (D) – straight lines along three edges, with an angle scale; drag the body to move, the handle to rotate",
        ["Color.Auto"] = "Default (black on light pages, white on dark ones)",
        ["Color.Custom"] = "Custom colour",
        ["Color.Pick"] = "Choose colour (colour wheel / hex)",
        ["Size.Tip"] = "Line width – press and hold for number entry",
        ["Action.Delete"] = "Delete",
        ["Action.Undo"] = "Undo (Ctrl+Z)",
        ["Action.Redo"] = "Redo (Ctrl+Y)",
        ["Zoom.Out"] = "Zoom out",
        ["Zoom.Reset"] = "Reset zoom",
        ["Zoom.In"] = "Zoom in",
        ["Wb.InsertFile"] = "Insert file",
        ["Wb.InsertFile.Tip"] = "Insert file – image, PDF or Word (pages selectable for PDF/Word; as new pages in a notebook, as image pages on a whiteboard); also via Ctrl+V or drag &amp; drop",
        ["Wb.Settings"] = "Settings",
        ["Wb.Settings.Tip"] = "Settings (page, shapes, text, cover)",
        ["Wb.Settings.PageTip"] = "Page settings (pattern, shade, size)",
        ["Wb.Settings.Close"] = "Close settings",
        ["Page.Previous"] = "Previous page",
        ["Page.Next"] = "Next page",
        ["Page.Add"] = "New page",
        ["Page.Delete"] = "Delete page",
        ["Page.Label"] = "Page {0} / {1}",
        ["Settings.Page"] = "Page",
        ["Settings.Page.Pattern"] = "Pattern",
        ["Settings.Page.Blank"] = "Blank",
        ["Settings.Page.Lines"] = "Ruled",
        ["Settings.Page.Grid"] = "Squared",
        ["Settings.Page.Dots"] = "Dotted",
        ["Settings.Page.Shade"] = "Shade",
        ["Settings.Page.Shade.Auto"] = "Follow app theme",
        ["Settings.Page.Shade.Light"] = "Light",
        ["Settings.Page.Shade.Dark"] = "Dark",
        ["Settings.Page.Format"] = "Format",
        ["Settings.Page.Orientation"] = "Orientation",
        ["Settings.Page.Portrait"] = "Portrait",
        ["Settings.Page.Landscape"] = "Landscape",
        ["Settings.Page.AsDefault"] = "Use as default for new pages",
        ["Settings.Page.CoverHint"] = "The cover has no pattern and no shade — its look comes from the cover settings.",
        ["Settings.Shapes"] = "Shapes",
        ["Settings.Shapes.Hint"] = "Pick the shape in the toolbar; set the fill here.",
        ["Settings.Shapes.FillToggle"] = "Fill on/off",
        ["Settings.Shapes.FillColor"] = "Choose fill colour",
        ["Settings.Shapes.Fill"] = "Fill",
        ["Settings.Shapes.Opacity"] = "Opacity",
        ["Settings.Text"] = "Text",
        ["Settings.Text.ColorTip"] = "Choose text colour (also used as ink colour)",
        ["Settings.Text.Color"] = "Text colour",
        ["Settings.Text.BgTip"] = "Background colour of the text box",
        ["Settings.Text.Bg"] = "Background",
        ["Settings.Text.Transparent"] = "Transparent",
        ["Settings.Text.Font"] = "Font",
        ["Settings.Text.Hint"] = "Applies to new text boxes and to the one being edited or selected.",
        ["Settings.Sticky"] = "Sticky notes",
        ["Settings.Sticky.Color"] = "Note colour",
        ["Settings.Sticky.CustomColor"] = "Choose a custom note colour",
        ["Settings.Sticky.Hint"] = "Tap the sheet to place a note, then tap it to write. Move/scale it with the move or lasso tool.",
        ["Settings.Sticker.Hint"] = "A click inserts the sticker in the middle of the sheet. Then place and scale it with the move tool (V).",
        ["Settings.Sticker.Add"] = "Add sticker",
        ["Settings.Sticker.Empty"] = "No stickers yet. Use “Add sticker” to add your own images.",
        ["Settings.Cover"] = "Cover",
        ["Settings.Cover.Gradient"] = "Gradient",
        ["Settings.Cover.StartColor"] = "Choose start colour",
        ["Settings.Cover.Start"] = "Start",
        ["Settings.Cover.EndColor"] = "Choose end colour",
        ["Settings.Cover.End"] = "End",
        ["Settings.Cover.Font"] = "Font",
        ["Settings.Cover.Image"] = "Image as cover",
        ["Settings.Cover.ChooseImage"] = "Choose image…",
        ["Settings.Cover.RemoveImage"] = "Remove",
        ["Settings.Cover.ImageHint"] = "The image replaces the gradient and the title on the cover.",
        ["Settings.Cover.Presets"] = "Templates",
        ["Settings.Cover.Add"] = "Add template",
        ["Quick.Cut.Tip"] = "Cut (Ctrl+X)",
        ["Quick.Cut"] = "Cut",
        ["Quick.Copy.Tip"] = "Copy (Ctrl+C)",
        ["Quick.Copy"] = "Copy",
        ["Quick.Duplicate.Tip"] = "Duplicate (Ctrl+D)",
        ["Quick.Duplicate"] = "Duplicate",
        ["Quick.Paste.Tip"] = "Paste (Ctrl+V)",
        ["Quick.Paste"] = "Paste",
        ["Quick.Ocr"] = "Recognise text (OCR)",
        ["Quick.Delete.Tip"] = "Delete (Del)",
        ["Quick.SelectAll.Tip"] = "Select all (Ctrl+A)",
        ["Quick.SelectAll"] = "Select all",
        ["Busy.Importing"] = "Importing…",
        ["Busy.Pdf"] = "Importing PDF…",
        ["Busy.Pdf.Progress"] = "Importing PDF…  {0} / {1}",
        ["Busy.Docx"] = "Inserting Word document…",
        ["Page.Cover"] = "Cover",
        ["Size.Eraser.Tip"] = "Eraser size – press and hold for number entry",

        // ---- Text editor ----
        ["Action.Undo.Short"] = "Undo",
        ["Action.Redo.Short"] = "Redo",
        ["Ed.Tab.Home"] = "Home",
        ["Ed.Tab.Insert"] = "Insert",
        ["Ed.Tab.Layout"] = "Layout",
        ["Ed.Tab.References"] = "References",
        ["Ed.Tab.Table"] = "Table",
        ["Ed.FormatPainter.Tip"] = "Format painter: click, then select the target",
        ["Ed.FormatPainter"] = "Format painter",
        ["Ed.ClearFormat"] = "Clear formatting",
        ["Ed.Font"] = "Font",
        ["Ed.FontSize"] = "Font size",
        ["Ed.FontGrow"] = "Increase font size",
        ["Ed.FontShrink"] = "Decrease font size",
        ["Ed.Bold"] = "Bold (Ctrl+B)",
        ["Ed.Italic"] = "Italic (Ctrl+I)",
        ["Ed.Underline"] = "Underline (Ctrl+U)",
        ["Ed.Strike"] = "Strikethrough",
        ["Ed.Subscript"] = "Subscript",
        ["Ed.Superscript"] = "Superscript",
        ["Ed.TextColor.Apply"] = "Apply text colour",
        ["Ed.TextColor.Pick"] = "Choose text colour",
        ["Ed.Highlight.Apply"] = "Apply highlighter",
        ["Ed.Highlight.Pick"] = "Choose highlighter colour (incl. “none”)",
        ["Ed.Align"] = "Text alignment",
        ["Ed.Align.Left"] = "Align left",
        ["Ed.Align.Center"] = "Centre",
        ["Ed.Align.Right"] = "Align right",
        ["Ed.Align.Justify"] = "Justify",
        ["Ed.List.Bullet"] = "Bulleted list",
        ["Ed.List.BulletPick"] = "Choose bullet character",
        ["Ed.List.Number"] = "Numbered list",
        ["Ed.List.NumberPick"] = "Choose numbering style",
        ["Ed.Indent.More"] = "Increase indent",
        ["Ed.Indent.Less"] = "Decrease indent",
        ["Ed.Styles.All"] = "All styles",
        ["Ed.Styles"] = "Styles",
        ["Ed.List.Bullets"] = "Bullets",
        ["Ed.List.Numbering"] = "Numbering",
        ["Ed.Table.Insert"] = "Insert table",
        ["Ed.Table.InsertDialog"] = "Insert table…",
        ["Ed.Table.FromText"] = "Convert text to table",
        ["Ed.Table.FromText.Tip"] = "Convert the selected text (separated by tab, semicolon or comma) into a table",
        ["Ed.Table.Quick"] = "Quick tables",
        ["Ed.Table.Quick.Calendar"] = "Calendar (month)",
        ["Ed.Table.Quick.List"] = "Simple list (with header row)",
        ["Ed.Image.Insert"] = "Insert image",
        ["Ed.Image"] = "Image",
        ["Ed.InfoBox.Tip"] = "Coloured info box (1×1 table with fill and border)",
        ["Ed.InfoBox.Insert"] = "Insert info box",
        ["Ed.InfoBox"] = "Info box",
        ["Ed.Rule"] = "— Divider",
        ["Ed.Symbol.Insert"] = "Insert special character",
        ["Ed.Symbol"] = "Special characters",
        ["Ed.Symbol.Button"] = " Ω Symbol ",
        ["Ed.Symbol.Group.Text"] = "Punctuation",
        ["Ed.Symbol.Group.Arrows"] = "Arrows",
        ["Ed.Symbol.Group.Math"] = "Mathematics",
        ["Ed.Symbol.Group.Greek"] = "Greek",
        ["Ed.Symbol.Group.Misc"] = "Other",
        ["Ed.Chart.Tip"] = "Insert a chart from your own values (bar, line, pie)",
        ["Ed.Chart"] = "Chart",
        ["Ed.HeaderFooter.Dialog"] = "Header/footer…",
        ["Ed.HeaderFooter"] = "Header and footer",
        ["Ed.PageNumbers"] = "Page numbers",
        ["Ed.Layout.Format"] = "Format",
        ["Ed.Layout.PaperSize"] = "Paper size",
        ["Ed.Layout.Letter"] = "Letter",
        ["Ed.Layout.Portrait"] = "Portrait",
        ["Ed.Layout.Portrait.Short"] = " Port. ",
        ["Ed.Layout.Landscape"] = "Landscape",
        ["Ed.Layout.Landscape.Short"] = " Land. ",
        ["Ed.Layout.Margins.Tip"] = "Set page margins",
        ["Ed.Layout.Margins"] = "Margins",
        ["Ed.Layout.Spacing.Tip"] = "Paragraph and line spacing",
        ["Ed.Layout.Spacing"] = "Spacing",
        ["Ed.Layout.Background.Tip"] = "Background image / watermark",
        ["Ed.Layout.Background"] = "Background image",
        ["Ed.Layout.PageBreaks"] = "Show page breaks",
        ["Ed.Layout.PageBreaks.Tip"] = "Shows approximately where the pages will break on PDF export",
        ["Ed.Toc.Insert.Tip"] = "Builds a table of contents from headings 1–4",
        ["Ed.Toc.Insert"] = "Insert table of contents",
        ["Ed.Toc.Update.Short"] = "Update",
        ["Ed.Toc.Update.Tip"] = "Rebuild the table of contents from the headings",
        ["Ed.Toc.Update"] = "Update table of contents",
        ["Ed.Link.Tip"] = "Insert/edit hyperlink",
        ["Ed.Link.Insert"] = "Insert link",
        ["Ed.Link"] = "Link",
        ["Ed.Caption.Tip"] = "Insert a caption “Figure N: …” below the image/paragraph",
        ["Ed.Caption.Insert"] = "Insert caption",
        ["Ed.Caption"] = "Caption",
        ["Ed.Caption.Prefix"] = "Figure",
        ["Action.Apply"] = "Apply",
        ["Ed.References.NoteName"] = "References note",
        ["Ed.References.Note"] = "On DOCX export the table of contents becomes a real Word field (with page numbers, updated on opening). Headings 1–4 appear in it automatically.",
        ["Ed.Table.Row"] = "Row",
        ["Ed.Table.Row.Above"] = "Insert row above",
        ["Ed.Table.Row.Below"] = "Insert row below",
        ["Ed.Table.Row.Delete"] = "Delete row",
        ["Ed.Table.Column"] = "Column",
        ["Ed.Table.Column.Left"] = "Insert column to the left",
        ["Ed.Table.Column.Right"] = "Insert column to the right",
        ["Ed.Table.Column.Delete"] = "Delete column",
        ["Ed.Table.Merge"] = "Merge",
        ["Ed.Table.Merge.Tip"] = "Merge the selected cells (horizontally, vertically or as a rectangle)",
        ["Ed.Table.Split"] = "Split",
        ["Ed.Table.Unmerge"] = "Unmerge cells",
        ["Ed.Table.SplitCell"] = "Split cell…",
        ["Ed.Table.SplitTable"] = "Split table (above the row)",
        ["Ed.Table.Sort"] = "Sort…",
        ["Ed.Table.Sort.Tip"] = "Sort rows by a column (text/number/date)",
        ["Ed.Table.Formula"] = "Formula…",
        ["Ed.Table.Formula.Tip"] = "Insert a calculation, e.g. =SUM(ABOVE) or =AVERAGE(LEFT)",
        ["Ed.Table.ToText"] = "To text…",
        ["Ed.Table.ToText.Tip"] = "Convert table to text",
        ["Ed.Table.Design.Tip"] = "Style, borders, fill and size in the sidebar",
        ["Ed.Table.Design"] = "Design &amp; borders…",
        ["Ed.Table.Delete"] = "Delete table",
        ["Ed.Table.NoteName"] = "Table note",
        ["Ed.Table.Note"] = "Limits of the text engine: cell borders are always solid (no dash styles), text in cells can only be aligned horizontally (approximate vertical alignment/row height via cell padding), no Excel embedding and no repeated header row across page breaks.",
        ["Ed.Find.Term"] = "Search term",
        ["Ed.Find.Next"] = "Next",
        ["Ed.Find.ReplaceWith"] = "Replace with",
        ["Ed.Find.Replace"] = "Replace",
        ["Ed.Find.ReplaceAll"] = "Replace all",
        ["Ed.Find.Close"] = "Close (Esc)",
        ["Ed.Find.Tip"] = "Find &amp; replace (Ctrl+F)",
        ["Ed.Find"] = "Find",
        ["Ed.Find.NotFound"] = "Not found",
        ["Ed.Find.Replaced"] = "{0} replaced",
        ["Ed.Status.Counts"] = "Words: 0 · Characters: 0",
        ["Ed.Spell.Language"] = "Spell-check language",
        ["Lang.German"] = "German",
        ["Lang.English"] = "English",
        ["Ed.Spell.Toggle"] = "Spell check on/off",
        ["Ed.Spell"] = "Spell check",
        ["Ed.Spell.Button"] = " ABC✓ ",
        ["Zoom.Out.Long"] = "Zoom out",
        ["Zoom.In.Long"] = "Zoom in",
        ["Ed.Navigator.Tip"] = "Heading navigator",
        ["Ed.Navigator"] = "Headings",
        ["Ed.Navigator.Empty"] = "No headings yet — mark a paragraph as a heading to see it here.",
        ["Ed.Advanced"] = "Advanced settings",
        ["Ed.Margins.Preset"] = "Preset",
        ["Ed.Margins.Normal"] = "Normal (2 cm)",
        ["Ed.Margins.Narrow"] = "Narrow (1.27 cm)",
        ["Ed.Margins.Wide"] = "Wide (3 cm)",
        ["Ed.Margins.Study"] = "Study sheet (4 cm left)",
        ["Ed.Margins.Custom"] = "Custom",
        ["Ed.Margins.Left"] = "Left",
        ["Ed.Margins.Top"] = "Top",
        ["Ed.Margins.Right"] = "Right",
        ["Ed.Margins.Bottom"] = "Bottom",
        ["Ed.Margins.Unit"] = "Values in cm",
        ["Ed.Paragraphs"] = "Paragraphs",
        ["Ed.Spacing.Before"] = "Space before",
        ["Ed.Spacing.After"] = "Space after",
        ["Ed.Spacing.Unit"] = "Spacing in pt",
        ["Ed.Spacing.Line"] = "Line spacing",
        ["Ed.Background.Choose"] = "Choose image…",
        ["Ed.Background.Tip"] = "Full-page image behind the text (watermark)",
        ["Ed.Background.Pick"] = "Choose background image",
        ["Ed.Opacity"] = "Opacity",
        ["Ed.Remove"] = "Remove",
        ["Ed.Table.Style"] = "Style",
        ["Ed.Table.HeaderRow"] = "Header row",
        ["Ed.Table.TotalRow"] = "Total row",
        ["Ed.Table.BandedRows"] = "Banded rows",
        ["Ed.Table.BandedColumns"] = "Banded columns",
        ["Ed.Table.Borders"] = "Borders of the selection",
        ["Ed.Table.Border.Width"] = "Thickness",
        ["Ed.Table.Border.Thin"] = "Thin (0.5)",
        ["Ed.Table.Border.Normal"] = "Normal (1)",
        ["Ed.Table.Border.Strong"] = "Strong (2)",
        ["Ed.Table.Border.Thick"] = "Thick (3.5)",
        ["Ed.Table.Border.All"] = "All",
        ["Ed.Table.Border.Outside"] = "Outside only",
        ["Ed.Table.Border.Inside"] = "Inside only",
        ["Ed.Table.Border.None"] = "None",
        ["Ed.Table.Border.Color"] = "Border colour…",
        ["Ed.Table.Fill"] = "Fill",
        ["Ed.Table.Fill.Color"] = "Fill colour…",
        ["Ed.Table.Size"] = "Size",
        ["Ed.Table.ColumnWidth"] = "Column width…",
        ["Ed.Table.AutoFit"] = "AutoFit",
        ["Ed.Table.AutoFit.Content"] = "Content",
        ["Ed.Table.AutoFit.Content.Tip"] = "Fit column widths to the content",
        ["Ed.Table.AutoFit.Page"] = "Page",
        ["Ed.Table.AutoFit.Page.Tip"] = "Stretch the table to the page width",
        ["Ed.Table.AutoFit.Fixed"] = "Fixed…",
        ["Ed.Table.AutoFit.Fixed.Tip"] = "Fixed column width in cm",
        ["Ed.Table.CellPadding"] = "Cell padding…",
        ["Ed.Table.CellPadding.Tip"] = "Inner spacing of the selected cells",
        ["Ed.Link.Edit"] = "Edit link…",
        ["Ed.Link.Remove"] = "Remove link",
        ["Ed.Object.Bigger"] = "Larger",
        ["Ed.Object.Smaller"] = "Smaller",
        ["Ed.Object.Wider"] = "Wider",
        ["Ed.Object.Narrower"] = "Narrower",
        ["Ed.Object.Taller"] = "Taller",
        ["Ed.Object.Shorter"] = "Shorter",
        ["Ed.Object.ExactSize"] = "Exact size…",
        ["Ed.Object.Behind"] = "Send behind text",
        ["Ed.Object.Front"] = "Bring in front of text",
        ["Ed.Table.MergeSelection"] = "Merge cells (selection)",
        ["Ed.Table.AllTools"] = "All table tools (ribbon tab)",

        // ---- Dialoge ----
        ["Dlg.Cancel"] = "Cancel",
        ["Dlg.Apply"] = "Apply",
        ["Dlg.Ok"] = "OK",
        ["Dlg.All"] = "All",
        ["Dlg.None"] = "None",
        // Gegenstuecke zu Dlg.Yes/Dlg.No in LocGerman (neu in Phase 3, siehe dort).
        // Gegenstueck zu Msg.Unexpected in LocGerman (§4.75).
        ["Msg.Unexpected"] =
            "An unexpected error occurred:\n\n{0}\n\n" +
            "The app keeps running. Details are in:\n{1}",
        ["Dlg.Yes"] = "Yes",
        ["Dlg.No"] = "No",
        // ---- Gegenstuecke zum Textdokument im Linux-Kopf in LocGerman (§4.28, siehe dort).
        // Tab.NoCanvasYet ist mit §4.28 weggefallen, die Registerkarte zeigt jetzt das
        // gesetzte Dokument.
        ["Io.NotOnThisPlatform"] =
            "This export is not available on this platform yet — it draws through the " +
            "Windows canvas and moves over with the Linux tools. Text documents can already " +
            "be exported here.",
        ["Io.NotMigrated"] =
            "This document comes from the Windows edition and has not been converted to the " +
            "built-in format yet. Conversion only runs there — opening and saving it once in " +
            "the Windows edition is enough.",
        ["Td.NotMigrated"] =
            "This document comes from the Windows edition and has not been converted to the " +
            "built-in format yet, so it cannot be shown here. Its contents are stored " +
            "unchanged. Open and save it once in the Windows edition and it will appear here " +
            "as well.",
        // Shown inside a table of contents with no headings yet — otherwise the
        // container would have no height and the field would be there but unfindable.
        ["Td.Toc.Empty"] = "Table of contents — no headings in this document yet",
        // Gegenstuecke zu Ed.ViewOnly* in LocGerman -- in Phase 5 zusammen entfallen, weil
        // im Linux-Kopf seit §4.35 geschrieben wird (siehe dort).
        ["Ed.TextOnly"] = "Text only",
        ["Ed.TextOnly.Tip"] =
            "You can write the text here: type, delete, select, undo. Formatting, tables and " +
            "pictures are still set in the Windows edition. What you see is exactly what " +
            "would be exported — same layout, same renderer.",
        // Gegenstuecke zu den drei neuen Reitern in LocGerman (§4.37, siehe dort).
        ["Ed.Break.Page"] = "Page break",
        ["Ed.Break.Page.Tip"] = "Continue on a new page from here",
        ["Ed.Break.Line"] = "Line break",
        ["Ed.Break.Line.Tip"] =
            "A new line inside the same paragraph (Shift+Enter) — paragraph spacing and list " +
            "marker stay untouched",
        ["Ed.Field"] = "Field",
        ["Ed.Field.Tip"] =
            "A spot whose content is calculated: page number, page count, date, title. It stays " +
            "correct after every change.",
        ["Ed.Field.PageNumber"] = "Page number",
        ["Ed.Field.PageCount"] = "Page count",
        ["Ed.Field.Date"] = "Date",
        ["Ed.Field.Title"] = "Document title",
        ["Ed.Table.Rows"] = "Rows",
        ["Ed.Table.Columns"] = "Columns",
        ["Ed.Link.Target"] = "Target",
        ["Ed.Link.Target.Tip"] =
            "Address of the link. If the caret sits inside an existing link, its target appears " +
            "here and can be changed.",
        ["Ed.Link.Set"] = "Set",
        ["Ed.Table.NotInTable"] =
            "Put the caret inside a table — its tools appear here.",
        // Gegenstuecke zu den Farbnamen in LocGerman (§4.40, `TdTextfarben`, siehe dort).
        ["Td.Color.Auto"] = "Automatic",
        ["Td.Color.None"] = "None",
        ["Td.Color.Red"] = "Red",
        ["Td.Color.Blue"] = "Blue",
        ["Td.Color.Green"] = "Green",
        ["Td.Color.Amber"] = "Amber",
        ["Td.Color.Purple"] = "Purple",
        ["Td.Color.Grey"] = "Grey",
        ["Td.Color.Yellow"] = "Yellow",
        ["Td.Color.Lime"] = "Lime",
        ["Td.Color.Cyan"] = "Cyan",
        ["Td.Color.Pink"] = "Pink",
        ["Td.Color.Sky"] = "Sky blue",
        ["Td.Color.Silver"] = "Silver",
        // Gegenstuecke zu Kopf-/Fusszeile in LocGerman (§4.40, siehe dort).
        ["Ed.HeaderFooter.Header"] = "Header",
        ["Ed.HeaderFooter.Footer"] = "Footer",
        ["Ed.HeaderFooter.SuppressFirst"] = "Omit on the first page",
        // Gegenstuecke zu Ed.HeaderFooter.Fields/Fields2/Example und Ed.PageNumbers.Tip in
        // LocGerman (§4.74). Die Platzhalter bleiben deutsch -- Begruendung siehe dort.
        ["Ed.HeaderFooter.Fields"] = "{SEITE} = page number · {SEITEN} = page count",
        ["Ed.HeaderFooter.Fields2"] = "{DATUM} = today's date · {TITEL} = document name",
        ["Ed.HeaderFooter.Example"] =
            "Example: Maths – Fractions · Year 6b · Page {SEITE}/{SEITEN}",
        ["Ed.PageNumbers.Tip"] = "Inserts “Seite {SEITE} von {SEITEN}” into the footer",
        // Gegenstuecke zu Ed.Page.NoUndo und Ed.Spacing.Scope in LocGerman (§4.38, siehe dort).
        ["Ed.Page.NoUndo"] =
            "Margins and paper size apply to the whole section and are not part of the undo " +
            "history — undo will not bring them back.",
        ["Ed.Spacing.Scope"] =
            "Applies to the paragraphs the selection touches.",
        // Gegenstuecke zu Td.RtfLeads* in LocGerman -- in Phase 5 zusammen entfallen, weil
        // §4.48 den Grund beseitigt hat und nicht nur die Warnung (siehe dort).
        ["Ed.Export"] = "Export",
        ["Ed.Export.Tip"] = "Write this document as PDF, Word, Markdown or PNG",
        ["Ed.FitWidth"] = "Fit width",
        ["Ed.FitWidth.Tip"] = "Set the zoom so the page fits the width",
        ["Ed.FitPage"] = "Whole page",
        ["Ed.FitPage.Tip"] = "Set the zoom so a whole page is visible",
        ["Td.HeaderFooter.Both"] = "both",
        ["Td.HeaderFooter.HeaderOnly"] = "header only",
        ["Td.HeaderFooter.FooterOnly"] = "footer only",
        ["Td.HeaderFooter.None"] = "none",
        ["Guide.Title"] = "Getting started",
        ["Guide.Heading"] = "Getting started with Gonk Note",
        ["Guide.Subtitle"] = "From your first note to your first backup — step by step.",
        ["About.Title"] = "About Gonk Note",
        ["About.Subtitle"] = "Offline notes, whiteboards and text documents. Your data lives on this machine only, inside your user folder.",
        // {0} = Versionsnummer. Gegenstueck zu About.Version in LocGerman — die Zeile stand
        // bisher fest verdrahtet im Code und erschien deshalb auch im englischen Dialog deutsch.
        // Sie sagt, woran gearbeitet wird, nicht was fertig ist; beide Tabellen zusammen aendern.
        ["About.Version"] = "Version {0} · Port, phase 5 — cleanup and release",
        // Gegenstueck zu Db.OpenFailed in LocGerman. {0} = Fehlermeldung, {1} = Protokollpfad.
        ["Db.OpenFailed"] =
            "The database could not be opened:\n\n{0}\n\n" +
            "Your existing data is not lost — the old database file is still in place, " +
            "unchanged. Details are in:\n{1}",
        ["Chart.Title"] = "Insert chart",
        ["Chart.Title.Edit"] = "Edit chart",
        ["Chart.Type"] = "Type",
        ["Chart.Type.Column"] = "Column",
        ["Chart.Type.Bar"] = "Bar",
        ["Chart.Type.Line"] = "Line",
        ["Chart.Type.Scatter"] = "Scatter",
        ["Chart.Type.ScatterLine"] = "Scatter + line",
        ["Chart.Type.Pie"] = "Pie",
        ["Chart.Type.Radar"] = "Radar",
        ["Chart.TitleField"] = "Title",
        ["Chart.Categories"] = "Categories",
        ["Chart.Categories.Example"] = "Jan, Feb, Mar, Apr",
        ["Chart.Categories.Hint"] = "Axis labels, separated by commas",
        ["Chart.SeriesNames"] = "Series names",
        ["Chart.Series.Example"] = "Series 1",
        ["Chart.SeriesNames.Hint"] = "one name per series, separated by commas (optional)",
        ["Chart.Values"] = "Values",
        ["Chart.Values.Hint"] = "one line per series/curve, values separated by commas",
        ["Chart.Values.Note"] = "Several series/curves: one series per line (Enter for a new line).",
        ["Chart.Colors"] = "Colours",
        ["Chart.Color.Change"] = "Change colour {0}",
        ["Chart.Color.Remove"] = "Remove colour",
        ["Chart.Color.Add"] = "Add a colour",
        ["Chart.Error.NoValues"] = "Please enter values (e.g. 4, 7, 3).",
        ["Chart.Error.RadarNeedsThree"] = "A radar chart needs at least three categories.",
        ["ColorPicker.Title"] = "Choose colour",
        ["ColorPicker.Hex"] = "Hex",
        ["HeaderFooter.Footer"] = "Footer",
        ["HeaderFooter.SkipFirst"] = "Hide on the first page (cover sheet)",
        ["HeaderFooter.Placeholders"] = "Placeholders:",
        ["Ocr.Title"] = "Text recognition",
        ["Ocr.Hint"] = "Recognised text – edit it if needed, copy it or insert it as a sticky note:",
        ["Ocr.AsSticky"] = "As sticky note",
        ["TableSize.Rows"] = "Rows",
        ["TableSize.Columns"] = "Columns",
        ["Sort.Title"] = "Sort table",
        ["Sort.By"] = "Sort by",
        ["Sort.Type.Number"] = "Number",
        ["Sort.Type.Date"] = "Date",
        ["Sort.Order"] = "Order",
        ["Sort.Ascending"] = "Ascending",
        ["Sort.Descending"] = "Descending",
        ["Sort.HeaderRow"] = "First row is a header (do not sort it)",
        ["Sort.Do"] = "Sort",
        ["Sort.Type.Text"] = "Text",

        // ---- Messages ----
        ["Msg.ImportFailed"] = "Import failed:",
        // The migration to the own document model runs silently — only a failure speaks up
        // (user decision 2026-08-05, HANDOFF §4.22). {0} = name, {1} = reason.
        ["Msg.MigrationFailed"] =
            "“{0}” could not be migrated to the new document format:\n{1}\n\n" +
            "The document is unchanged and can still be edited — " +
            "the attempt will be repeated the next time it is opened.",
        ["Msg.OpenDocumentFirst"] = "Please open a document first.",
        ["Msg.ExportFailed"] = "Export failed:\n{0}",
        ["Msg.ExportedPages"] = "{0} pages exported to:\n{1}\n\nOpen the first file?",
        ["Msg.ExportedFile"] = "Exported to:\n{0}\n\nOpen the file now?",
        ["Settings.Export"] = "Export",
        ["Settings.Export.Hint"] = "Exports this document with all its pages.",
        ["Settings.Export.Pdf"] = "Export as PDF …",
        ["Settings.Export.Png"] = "Export as PNG …",
        ["Msg.ValidationHint"] = "\n\nNote: OpenXML validation reports {0} item(s).",
        ["Msg.ExportImagesMissing"] = "\n\nWarning: data is missing for {0} image(s). They appear in " +
            "the export as placeholders or at reduced quality. Check that your backup of the " +
            "\"gonknote.blobs\" folder next to the database is complete.",
        ["Msg.DeleteFolder"] = "Delete the folder “{0}” and all of its contents?",
        ["Msg.DeleteItem"] = "Delete “{0}”?",
        ["Msg.DeletePage"] = "Delete this page and its contents?",
        ["Msg.ImageLoadFailed"] = "The image could not be loaded:\n{0}",
        ["Msg.ImageLoadSimple"] = "The image could not be loaded.",
        ["Msg.InvalidUrl"] = "The address is not a valid URL.",
        ["Msg.UrlPrompt"] = "Address (URL):",
        ["Msg.MergeSameTable"] = "To merge, please select cells within the same table.",
        ["Msg.NoToc"] = "No table of contents found. Please create one first via “Insert table of contents”.",
        ["Msg.SelectTextFirst"] = "Please select the text to convert first.",
        ["Msg.SplitNeedsSecondRow"] = "The cursor must be in the second row or below (the table is split above that row).",
        ["Msg.SplitAcrossMerge"] = "A row merge crosses the split point here – please unmerge it first.",
        ["Msg.SortWithMerge"] = "Tables with merged rows cannot be sorted – please unmerge them first.",
        ["Msg.FormulaUnknown"] = "Formula not recognised. Supported: SUM, AVERAGE, MIN, MAX, COUNT, PRODUCT over ABOVE, BELOW, LEFT or RIGHT.",
        ["Msg.NoNumbers"] = "There are no numbers in the selected range.",
        ["Msg.TableSize"] = "{0} × {1} table",
        ["Msg.StyleName"] = "Style {0}",
        ["Msg.PresetDeleteFailed"] = "The template could not be deleted:\n{0}",
        ["Msg.PresetLoadFailed"] = "The template could not be loaded:\n{0}",
        ["Msg.LoadFailed"] = "Could not be loaded:",
        ["Msg.PdfNoPages"] = "The PDF contains no displayable pages.",
        ["Msg.PdfLoadFailed"] = "The PDF could not be loaded:\n{0}",
        ["Msg.DocxNoPages"] = "The Word document contains no displayable pages.",
        ["Msg.DocxLoadFailed"] = "The Word document could not be loaded:\n{0}",
        ["Msg.OcrNoText"] = "No text was recognised.",
        ["Msg.OcrFailed"] = "Text recognition failed:\n{0}",
        ["Msg.OcrRunning"] = "Recognising text…",
        ["Msg.OcrRunningMany"] = "Recognising text…  (several images)",
        ["Msg.StickerFailed"] = "The sticker could not be inserted:\n{0}",
        ["Msg.PageN"] = "Page {0}",
        ["Dialog.ChoosePages"] = "Choose pages – {0}",
        ["Msg.PagesHint"] = "{0} pages · click a page to select/deselect it",
        ["Msg.InsertOnePage"] = "Insert 1 page",
        ["Msg.InsertPages"] = "Insert {0} pages",

        // ---- Paragraph styles ----
        ["Style.Normal"] = "Normal",
        ["Style.NoSpacing"] = "No spacing",
        ["Style.Heading1"] = "Heading 1",
        ["Style.Heading2"] = "Heading 2",
        ["Style.Heading3"] = "Heading 3",
        ["Style.Heading4"] = "Heading 4",
        ["Style.Title"] = "Title",
        ["Style.Quote"] = "Quote",
        ["Style.Header"] = "Header",
        ["Style.Footer"] = "Footer",
        ["Msg.HeadingTip"] = "{0} (Ctrl+Alt+{1}) – appears in the table of contents",
        ["Ed.Status.Counts.Format"] = "Words: {0} · Characters: {1}",
        ["Msg.NoDictionary"] = "Windows has no spelling dictionary installed for {0}, so no mistakes are marked. Add the language in the Windows settings: Time & language → Language & region → Add a language (including spelling).",

        // ---- Table styles ----
        ["TStyle.Plain"] = "Plain (grid)",
        ["TStyle.Blue"] = "Blue",
        ["TStyle.Teal"] = "Teal",
        ["TStyle.Purple"] = "Purple",
        ["TStyle.Gray"] = "Grey",
        ["TStyle.Warm"] = "Warm (yellow)",
        ["TStyle.Borderless"] = "No borders",
    };
}
